"""adiciona_cpf_cliente

Revision ID: 2259dbee1851
Revises: aac6682367fe
Create Date: 2026-06-18 17:24:05.307627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2259dbee1851'
down_revision: Union[str, Sequence[str], None] = 'aac6682367fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('cpf', sa.String(length=14), nullable=True))
    op.create_unique_constraint(None, 'clientes', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='unique')
    op.drop_column('clientes', 'cpf')
    # ### end Alembic commands ###
