"""criacao_inicial

Revision ID: aac6682367fe
Revises: 
Create Date: 2026-06-18 17:21:59.209704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac6682367fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_veiculos_id'), 'veiculos', ['id'], unique=False)
    op.create_table('locacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('data_locacao', sa.Date(), nullable=False),
    sa.Column('data_devolucao', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locacoes_id'), 'locacoes', ['id'], unique=False)
    op.create_table('historico_locacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locacao_id', sa.Integer(), nullable=True),
    sa.Column('status_anterior', sa.String(length=20), nullable=False),
    sa.Column('status_novo', sa.String(length=20), nullable=False),
    sa.Column('data_alteracao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['locacao_id'], ['locacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_locacoes_id'), 'historico_locacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_locacoes_id'), table_name='historico_locacoes')
    op.drop_table('historico_locacoes')
    op.drop_index(op.f('ix_locacoes_id'), table_name='locacoes')
    op.drop_table('locacoes')
    op.drop_index(op.f('ix_veiculos_id'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
